CREATE TABLE "ifc" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR2(255) NOT NULL,
    "content" BLOB
  );

CREATE TABLE "frag" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR2(255) NOT NULL,
    "content" BLOB
  );

CREATE TABLE "bcf" (
"id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" VARCHAR2(255) NOT NULL,
"content" BLOB
);

CREATE TABLE "ifc_bcf" (
    "ifc_id" NUMBER NOT NULL,
    "bcf_id" NUMBER NOT NULL,
    CONSTRAINT "pk_ifc_bcf" PRIMARY KEY ("ifc_id", "bcf_id"),
    CONSTRAINT "fk_ifc_bcf_ifc" FOREIGN KEY ("ifc_id") REFERENCES "ifc"("id"),
    CONSTRAINT "fk_ifc_bcf_bcf" FOREIGN KEY ("bcf_id") REFERENCES "bcf"("id")
);

SELECT
  (SELECT COUNT(*) FROM "ifc") AS ifc_total_count,
  (SELECT COUNT(*) FROM "frag") AS frag_total_count,
  (SELECT COUNT(*) FROM "bcf") AS bcf_total_count,
  (SELECT COUNT(*) FROM "ifc_bcf") AS ifc_bcf_total_count
FROM DUAL;


DROP TABLE "ifc_bcf";

DROP TABLE "bcf";

DROP TABLE "frag";

DROP TABLE "ifc";

SELECT version, version_full FROM v$instance;

SELECT * FROM v$nls_parameters WHERE parameter LIKE '%CHARACTERSET%';