CREATE TABLE "ifc" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR2(255) NOT NULL,
    "content" BLOB
  );

CREATE TABLE "frag" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR2(255) NOT NULL,
    "content" BLOB
  );

CREATE TABLE "bcf" (
"id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" VARCHAR2(255) NOT NULL,
"content" BLOB,
"ifcid" NUMBER NOT NULL,
CONSTRAINT "fk_bcf_ifc" FOREIGN KEY ("ifcid") REFERENCES "ifc"("id")
);

SELECT
  (SELECT COUNT(*) FROM "ifc") AS ifc_total_count,
  (SELECT COUNT(*) FROM "frag") AS frag_total_count,
FROM DUAL;


DROP TABLE "bcf";

DROP TABLE "frag";

DROP TABLE "ifc";

DROP TABLE "ifc_manager";

SELECT version, version_full FROM v$instance;

SELECT * FROM v$nls_parameters WHERE parameter LIKE '%CHARACTERSET%';